// Regenerates src/title-glyphs.ts from the bundled Orbitron Black: node --experimental-strip-types scripts/title-glyphs.ts
import { readFileSync, writeFileSync } from "node:fs";
import opentype from "opentype.js";

const buf = readFileSync("node_modules/@fontsource/orbitron/files/orbitron-latin-900-normal.woff");
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
const scale = 1000 / font.unitsPerEm;
const lines: string[] = [];
for (const ch of "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789") {
  const g = font.charToGlyph(ch);
  const d = g.getPath(0, 0, 1000).toPathData(1);
  lines.push(`  ${JSON.stringify(ch)}: { advance: ${Math.round(g.advanceWidth! * scale)}, d: ${JSON.stringify(d)} },`);
}
const capHeight = Math.round((font.tables.os2 as unknown as { sCapHeight: number }).sCapHeight * scale);
writeFileSync("src/title-glyphs.ts", `// Generated by scripts/title-glyphs.ts: Orbitron Black outlines, 1000 units per em, SVG y-down from the baseline.
export const CAP_HEIGHT = ${capHeight};
export const GLYPHS: Record<string, { advance: number; d: string }> = {
${lines.join("\n")}
};
`);
